---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubo:route-sync
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubo:internal:route-sync
subjects:
- kind: User
  name: route-sync
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: kubo:route-sync
  apiGroup: rbac.authorization.k8s.io
