- path: /releases
  type: replace
  value:
  - name: kubo
    sha1: 75c351e626de164c8f94be4c0a66bb2e427e14f3
    url: https://github.com/cloudfoundry-incubator/kubo-release/releases/download/v0.30.0/kubo-release-0.30.0.tgz
    version: 0.30.0
  - name: cfcr-etcd
    sha1: e752e3b97491a65c3db2d06cda4227213c74472b
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/cfcr-etcd-release?v=1.10.0
    version: 1.10.0
  - name: docker
    sha1: c8c224ee789783ee04943e76ba9355a2bf80e0cb
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/docker-boshrelease?v=35.1.0
    version: 35.1.0
  - name: bpm
    sha1: 2875a69cae225fa97fe3faae1e9fbacff61e2dc5
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=1.0.3
    version: 1.0.3
