---
- type: remove
  path: /variables/name=tls-kubernetes

- type: replace
  path: /variables/-
  value:
    name: kubo-master-ca
    type: certificate
    options:
      is_ca: true
      common_name: kubo-master-ca

- type: replace
  path: /variables/-
  value:
    name: tls-kubernetes
    type: certificate
    options:
      ca: kubo-master-ca
      organization: "system:masters"
      common_name: master.cfcr.internal
      alternative_names:
      - 10.100.200.1
      - kubernetes
      - kubernetes.default
      - kubernetes.default.svc
      - kubernetes.default.svc.cluster.local
      - master.cfcr.internal

